# Copyright (C) 2021 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU Affero General Public License version 3.0 or later

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.23.2
    hooks:
      - id: pyupgrade
        args: ['--py36-plus']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: '\.svg$'
      - id: trailing-whitespace
        exclude: '\.wxf$'

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/google/yapf
    rev: v0.31.0
    hooks:
      - id: yapf
