#! /usr/bin/env python2
# Copyright (C) 2014 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU Affero General Public License version 3.0 or later

from xiangqi_setup.cli import main
main()
