# Copyright (C) 2021 Sebastian Pipping <sebastian@pipping.org>
# Licensed under CC0-1.0

allow_scaling:
  arrow_minus_1_minus_1: false
  arrow_minus_1_minus_2: false
  arrow_minus_1_plus_0: false
  arrow_minus_1_plus_1: false
  arrow_minus_1_plus_2: false
  arrow_minus_2_minus_1: false
  arrow_minus_2_minus_2: false
  arrow_minus_2_plus_0: false
  arrow_minus_2_plus_1: false
  arrow_minus_2_plus_2: false
  arrow_minus_3_plus_0: false
  arrow_minus_4_plus_0: false
  arrow_minus_5_plus_0: false
  arrow_minus_6_plus_0: false
  arrow_minus_7_plus_0: false
  arrow_minus_8_plus_0: false
  arrow_plus_0_minus_1: false
  arrow_plus_0_minus_2: false
  arrow_plus_0_minus_3: false
  arrow_plus_0_minus_4: false
  arrow_plus_0_minus_5: false
  arrow_plus_0_minus_6: false
  arrow_plus_0_minus_7: false
  arrow_plus_0_minus_8: false
  arrow_plus_0_minus_9: false
  arrow_plus_0_plus_1: false
  arrow_plus_0_plus_2: false
  arrow_plus_0_plus_3: false
  arrow_plus_0_plus_4: false
  arrow_plus_0_plus_5: false
  arrow_plus_0_plus_6: false
  arrow_plus_0_plus_7: false
  arrow_plus_0_plus_8: false
  arrow_plus_0_plus_9: false
  arrow_plus_1_minus_1: false
  arrow_plus_1_minus_2: false
  arrow_plus_1_plus_0: false
  arrow_plus_1_plus_1: false
  arrow_plus_1_plus_2: false
  arrow_plus_2_minus_1: false
  arrow_plus_2_minus_2: false
  arrow_plus_2_plus_0: false
  arrow_plus_2_plus_1: false
  arrow_plus_2_plus_2: false
  arrow_plus_3_plus_0: false
  arrow_plus_4_plus_0: false
  arrow_plus_5_plus_0: false
  arrow_plus_6_plus_0: false
  arrow_plus_7_plus_0: false
  arrow_plus_8_plus_0: false
  blank_bad: true
  blank_good: true
  blank_move: true
  piece_bad: true
  piece_good: true
  piece_move: false

draw_above_pieces:
  arrow_minus_1_minus_1: true
  arrow_minus_1_minus_2: true
  arrow_minus_1_plus_0: true
  arrow_minus_1_plus_1: true
  arrow_minus_1_plus_2: true
  arrow_minus_2_minus_1: true
  arrow_minus_2_minus_2: true
  arrow_minus_2_plus_0: true
  arrow_minus_2_plus_1: true
  arrow_minus_2_plus_2: true
  arrow_minus_3_plus_0: true
  arrow_minus_4_plus_0: true
  arrow_minus_5_plus_0: true
  arrow_minus_6_plus_0: true
  arrow_minus_7_plus_0: true
  arrow_minus_8_plus_0: true
  arrow_plus_0_minus_1: true
  arrow_plus_0_minus_2: true
  arrow_plus_0_minus_3: true
  arrow_plus_0_minus_4: true
  arrow_plus_0_minus_5: true
  arrow_plus_0_minus_6: true
  arrow_plus_0_minus_7: true
  arrow_plus_0_minus_8: true
  arrow_plus_0_minus_9: true
  arrow_plus_0_plus_1: true
  arrow_plus_0_plus_2: true
  arrow_plus_0_plus_3: true
  arrow_plus_0_plus_4: true
  arrow_plus_0_plus_5: true
  arrow_plus_0_plus_6: true
  arrow_plus_0_plus_7: true
  arrow_plus_0_plus_8: true
  arrow_plus_0_plus_9: true
  arrow_plus_1_minus_1: true
  arrow_plus_1_minus_2: true
  arrow_plus_1_plus_0: true
  arrow_plus_1_plus_1: true
  arrow_plus_1_plus_2: true
  arrow_plus_2_minus_1: true
  arrow_plus_2_minus_2: true
  arrow_plus_2_plus_0: true
  arrow_plus_2_plus_1: true
  arrow_plus_2_plus_2: true
  arrow_plus_3_plus_0: true
  arrow_plus_4_plus_0: true
  arrow_plus_5_plus_0: true
  arrow_plus_6_plus_0: true
  arrow_plus_7_plus_0: true
  arrow_plus_8_plus_0: true
  blank_bad: true
  blank_good: true
  blank_move: true
  piece_bad: true
  piece_good: true
  piece_move: false
